config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about/index'
  # get 'authors/index'
  # get 'authors/show'
  # get 'books/index'
  # get 'books/show'

  # Both of these will go to the main "root" page
  root to: 'books#index'
  # get 'books', to: 'books#index'

  resources 'books', only: %i[index show]
  # GET /books      => books#index
  # GET /books/:id  => books#show

  resources 'authors', only: %i[index show]
  # GET /authors      => authors#index
  # GET /authors/:id  => authors#show

  resources 'about', only: %i[index]

  get 'search', to: 'books#search', as: 'search'
  # get 'authors', to: 'authors#index, as: ...'
  # get 'books/:id', to: 'books#show', id: /\d+/, as: 'book' # book_path
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_and_belongs_to_many :books # Many to many association

  validates :name, presence: true
  # Note: Implicit requirement for FK since it
  #       belongs to the Book class
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_and_belongs_to_many :authors # Many to many association

  validates :booktitle, presence: true
  validates :pages, numericality: { only_integer: true }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  # GET /authors
  # We're also taking care of any potential N+1 issues
  # Future consideration: better way to put it?
  def index
    @authors = Author.includes(:books).order(:name)
  end
  # Automatically loads view:
  # views/authors/index.html.erb

  # GET /authors/:id    => params[:id]
  def show
    @author = Author.find(params[:id])
  end
  # Automatically loads view:
  # views/authors/show.html.erb
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.order(:booktitle).page params[:page]
  end

  # GET /books/:id (May need to change :id to something else)
  def show
    @book = Book.find(params[:id])
  end

  # Search action
  def search
    @books = Book.where('booktitle LIKE ?', "%#{params[:booktitle]}%").page params[:page]
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/authors/index.html.erb
<h2>All Authors</h2>

<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<h2><%= @author.name %></h2>
<p>This author has written the following books:</p>
<ul>
  <% @author.books.each do |book| %>
    <% if @author.name == book.authors.first.name %>
      <li><%= book.booktitle %></li>
    <% end %>
  <% end %>
</ul>

app/views/books/index.html.erb
<% if @books.empty? %>
  <p>No books available.</p>
<% else %>
      <div class="row">

      <% @books.each do |book| %>
        <div class="col-sm-4">
      <div class="card" style="width: 18rem; display:inline-block">
        <div class="card-body">
        <h5 class="card-title"><%= link_to book.booktitle, book %></h5>
        <p class="card-text"><p>Author: <%= link_to book.authors.first.name, author_path(book.authors.first.id) %></p>
        <p>Average Rating: <%= book.avgrating %></p>
        <p>Pages: <%= book.pages %></p></p>
        <%# <%= link_to "Book Details", book %>
        </div>
        </div>
      </div>
  <% end %>
  </div>
<% end %>

<%= paginate @books %>

app/views/books/search.html.erb
<% if @books.empty? %>
  <p>No books available.</p>
<% else %>
      <div class="row">

      <% @books.each do |book| %>
        <div class="col-sm-4">
      <div class="card" style="width: 18rem; display:inline-block">
        <div class="card-body">
        <h5 class="card-title"><%= link_to book.booktitle, book %></h5>
        <p class="card-text"><p>Author: <%= link_to book.authors.first.name, author_path(book.authors.first.id) %></p>
        <p>Average Rating: <%= book.avgrating %></p>
        <p>Pages: <%= book.pages %></p></p>
        <%# <%= link_to "Book Details", book %>
        </div>
        </div>
      </div>
  <% end %>
  </div>
<% end %>

<%= paginate @books %>

app/views/books/show.html.erb
<h2><%= @book.booktitle %></h2>
  <p>Author: <%= @book.authors.first.name %></p>
  <p>Average Rating: <%= @book.avgrating %></p>
  <p>Pages: <%= @book.pages %></p>

<h3></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Great Books App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-yrfSO0DBjS56u5M+SjWTyAHujrkiYVtRYh2dtB3yLQtUz3bodOeialO59u5lUCFF" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/books">Books To Read</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/books">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="/authors">Authors</a>
          <a class="nav-item nav-link" href="/about">About</a>
        </div>
      </div>

      <form class="form-inline" action="/search">
        <input class="form-control mr-sm-2" name="booktitle" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <footer>
      Thank you for visiting.
    </footer>
  </body>
</html>